### ISSUE TITLE
按时长分段保存, 提供一个简单粗暴的办法

### ISSUE THREAD

**Issue by cxumol** [hr3lxphr6j/bililive-go#105]
原理是, 让另一个软件控制录制软件, 使后者隔一段时间重启一下, 间隔时间可以自行设定｡ 

下载 https://github.com/cxumol/interval-restarter/releases 到 bililive-go 同一目录下
然后创建/修改配置文件 cfg.yml , 比如

```yaml
start: ./bililive-go -i "https://www.douyu.com/123456" -o "/home/username/cloud_drive_mount" --debug  --native-flv-parser --interval=10
end: pkill -SIGINT -f "bil.*?douyu.com/123456"
interval: 1h
shell: bash 
```

- start 处填写启动命令
- end 处填写关闭命令 (比如 `pkill`) 
- interval 填写你想要重启的间隔, 比如 `1h23m45s` 代表一小时二十三分四十五秒, 支持的单位有 "ns", "us"/"µs", "ms", "s", "m", "h"
- shell 写你在用的 shell 名字; windows 可以试试 powershell , 反正 cmd 不行

然后, 启动运行 `./intrvl-r -c "./cfg.yml"`, 就能让 `bililive-go` 隔一段时间重启一下

终端可以观看到 `intrvl-r` 以及 `bililive-go` 两个程序的 log
