### ISSUE TITLE
可否增加功能

### ISSUE THREAD

**Issue by ixinshang** [hr3lxphr6j/bililive-go#154]
1：支持m3u8格式的播放链接
2：增加对每个任务的定时任务（定时开/定时关）
最后，感谢开发这个好用的工具。

**Comment by hr3lxphr6j** [comment]
1. m3u8是支持的，Twitch就是
2. 这样配置可以接受吗
    ```cron
    0 20 * * * live.Start(http://live.bilibili.com/6)
    0 22 * * * live.Stop(http://live.bilibili.com/6)
    ````

**Comment by ixinshang** [comment]
@hr3lxphr6j    谢谢回复。
可以的，我目前用着docker下使用的，很不错。 
另外，有对录制文件进行分割的计划吗？
录制了1个视频，10+G。

**Comment by hr3lxphr6j** [comment]
> @hr3lxphr6j 谢谢回复。
> 可以的，我目前用着docker下使用的，很不错。
> 另外，有对录制文件进行分割的计划吗？
> 录制了1个视频，10+G。

分割目前有按时间分割 https://github.com/hr3lxphr6j/bililive-go/wiki/More-Tips
```yaml
video_split_strategies:   # 分隔策略
    on_room_name_changed: false    # 是否在直播间名改变时分隔录像
    max_duration: 1h               # 单个录像最大时长
```
