### ISSUE TITLE
长时间录制任务消失问题

### ISSUE THREAD

**Issue by capric98** [hr3lxphr6j/bililive-go#17]
使用的版本: 0.22.12
平台：Ubuntu 18.04 + ffmpeg version 3.4.4-0ubuntu0.18.04.1

### 问题描述
使用rpc方法添加的任务长时间录制后可能会突然消失
config.yml
```yaml
rpc: 
  enable: true
  port: 127.0.0.1:6161
  token: "blablabla"
  tls:
    enable: false
    cert_file: ""
    key_file: ""
debug: false
interval: 5
out_put_path: /Record
```
使用自己写的[简易客户端](https://github.com/DeveloperHZH/Bililive-go-Python-Client)添加上一个虎牙的录制任务，然后使用crontab每小时运行一次客户端的暂停、开始功能，但是录制任务有时候会消失；后来我写了个check的脚本每天check两次有没有任务，在这个脚本运行的第4天和第22天出现了任务消失的情况……服务器和bililive-go都没有重启过……
[check.log](https://github.com/hr3lxphr6j/bililive-go/files/3089757/check.log)
↑我比较弱智，log忘记输出日期了
