### ISSUE TITLE
请问可以单独为一个房间增加转码选项吗

### ISSUE THREAD

**Issue by aohaki** [hr3lxphr6j/bililive-go#339]
### 新功能

录制自用asmr的视频太长了，想单独转成音频同时不影响其他主播的视频录制

**Comment by kira1928** [comment]
以前也有人提过类似的建议（[一](https://github.com/hr3lxphr6j/bililive-go/issues/29)，[二](https://github.com/hr3lxphr6j/bililive-go/issues/206)），当时的结论是用户那边自己用 ffmpeg 转换一下就好了。
不过到现在第三次有人提这个问题了，也许这确实是一个有一定用户需求的功能。。
这里想问一下，你会用 ffmpeg 命令吗？我想如果给房间增加一个录制结束后执行特定命令的设置，然后你在里面写 ffmpeg 的命令执行你觉得怎么样？
比如
```yaml
live_rooms:
- url: https://www.huya.com/991111
  is_listening: true
  run_after_record: "ffmpeg -i $INPUT -vn -acodec copy $INPUT.m4a && rm $INPUT"
```
这样。
