### ISSUE TITLE
每次Docker镜像更新后，config配置会重新创建一份，需要手动迁移

### ISSUE THREAD

**Issue by bulai0408** [hr3lxphr6j/bililive-go#357]
### 程序版本

0.7.3

### 所使用的 config 文件的内容
```yaml
rpc:
  enable: true
  bind: 0.0.0.0:8080
debug: false
interval: 15
out_put_path: /srv/bililive
feature:
  use_native_flv_parser: false
live_rooms:
- url: https://www.douyu.com/5092355
  is_listening: true
- url: https://www.huya.com/24129960
  is_listening: true
- url: https://live.bilibili.com/1322433
  is_listening: true
- url: https://www.huya.com/23619220
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000
```

### 自由描述

如题，能否将config也放在docker的volume中，这样就能持久化配置
