### ISSUE TITLE
[提问]: 请教下cookie的书写方式

### ISSUE THREAD

**Issue by swRains** [hr3lxphr6j/bililive-go#419]
### 程序版本

0.7.8

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.bilibili.com/22909081
  is_listening: true
- url: https://www.huya.com/949527
  is_listening: true
- url: https://www.huya.com/52988
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 2h0m0s
cookies:
  ? live.bilibili.com:innersign=0; buvid3=E1376724-C*********************************************
  : ""
  ? live.douyin.com:__ac_nonce=0640ed******; __ac_signature=_02B4Z6*****;
  : ""
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 自由描述

请教下cookie的书写规范，按照您的readme，cookie应该写为
cookies:
     live.***.com:cookies

但是我这样写似乎保存不了，只有前面加？才能保存，而且每个cookie下自动会补全一行  【: ""】，我想请教下相关用法，是不是这个可以指定哪些直播间使用cookies？

**Comment by kira1928** [comment]
应该是因为你缺少空格吧。
是是这样？
```yaml
cookies:
  live.bilibili.com: innersign=0; buvid3=E1376724-C*********************************************
  live.douyin.com: __ac_nonce=0640ed******; __ac_signature=_02B4Z6*****;
```
