### ISSUE TITLE
无法正常开始录制

### ISSUE THREAD

**Issue by a136369618483** [hr3lxphr6j/bililive-go#441]
### 程序版本

v0.7.10

### 所使用的 config 文件的内容
```yaml
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 20
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
live_rooms:
# qulity参数目前仅B站启用，默认为0
# (B站)0代表原画PRO(HEVC)优先, 其他数值为原画(AVC)
# 原画PRO会保存为.ts文件, 原画为.flv
# HEVC相比AVC体积更小, 减少35%体积, 画质相当, 但是B站转码有时候会崩
- url: https://www.lang.live/room/5664344
  is_listening: false
- url: https://live.bilibili.com/22603245
  is_listening: true
  quality: 0 
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000
```

### 程序 log

E:\screen recorder\bililive-go>bililive-go.exe -c ./config.yml
time="2023-04-17 11:39:46" level=info msg="BiliLive-go Version: v0.7.10 Link Start"
time="2023-04-17 11:39:46" level=debug msg="config path: ./config.yml."
time="2023-04-17 11:39:46" level=debug msg="other flags have been ignored."
time="2023-04-17 11:39:46" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.10 BuildTime:2023-04-16_14:28:49 GitHash:54540bfc76d41baaa1fdece108f66eb35e04dc70 Pid:25180 Platform:windows/amd64 GoVersion:go1.19.8}"
time="2023-04-17 11:39:46" level=debug msg="&{File:./config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:20 OutPutPath:./ Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false} LiveRooms:[{Url:https://www.lang.live/room/5664344 IsListening:false LiveId: Quality:0} {Url:https://live.bilibili.com/22603245 IsListening:true LiveId: Quality:0}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.bilibili.com/22603245:1 https://www.lang.live/room/5664344:0]}"
time="2023-04-17 11:39:47" level=info msg="Server start at 127.0.0.1:8080"

### 自由描述

你好，在第一次使用时可以正常录制。但是使用时，录制地址在直播也未开始正常录制。我需要如何定位这个问题，debug信息并没有看到什么有用的信息
