### ISSUE TITLE
录制完成后支持自定义ffmpeg参数

### ISSUE THREAD

**Issue by Lua12138** [hr3lxphr6j/bililive-go#522]
### 新功能

在配置文件中大概可以这样表述：
```yml
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: true
  custom_ffmpeg_args: -acodec aac -vcodec libx265 {{ .Live.GetPlatformCNName }}_{{ .HostName }}_{{ now | date "2006-01-02 15-04-05"}}.mp4
```

相当于允许用户可以hook到完成的录制的事件，并按照自己愿意的方式重新组织。

在代码上可以简单`fmt.Sprintf("ffmpeg -i <ORIGIN_FILE> %s", custom_ffmpeg_args)`

当然通过WebHook的方式通知外部应用也是一种方案，但是多数使用者我想应该用不到，能够自定义ffmpeg参数，而不是简单的转换到MP4，应该足以满足绝大多数需求。同时开发难度也并不大。

如果开发者觉得这项提议有意义的话，我也很愿意贡献相关的代码。
