### ISSUE TITLE
[v0.8.0-danmu] panic: close of closed channel

### ISSUE THREAD

**Issue by kira1928** [hr3lxphr6j/bililive-go#558]
### 程序版本

v0.8.0-danmu

### 所使用的 config 文件的内容

```yaml
rpc:
  enable: true
  bind: :8080
debug: true
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.bilibili.com/22603245
  is_listening: true
  quality: 0
- url: https://www.douyu.com/606118
  is_listening: true
  quality: 0
- url: https://www.huya.com/518518
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
danmu:
  enable: true

```

### 程序 log

```
	/projects/bililive-go-2/src/recorders/recorder.go:375 +0xc5
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Start

	/projects/bililive-go-2/src/recorders/recorder.go:252 +0x39
"github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).run(0xc000222f00, {0x16abd58, 0xc0003c66f0})"

	/projects/bililive-go-2/src/recorders/recorder.go:170 +0xc90
"github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).tryRecord(0xc000222f00, {0x16abd58?, 0xc0003c66f0})"

goroutine 59040 [running]:

panic: close of closed channel
```

### 自由描述

在群晖 NAS 的 docker compose 中运行时发生。
