### ISSUE TITLE
抖音原画录制间歇性异常

### ISSUE THREAD

**Issue by ransxd** [hr3lxphr6j/bililive-go#563]
### 程序版本

0.7.18(docker)

### 所使用的 config 文件的内容
```yaml
rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/zbcll0715
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies:
  live.douyin.com: __ac_nonce=065*******2735;name=value
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
```

### 程序 log
```
root@VM-166-4-ubuntu:~# docker logs 4f5bdc759be6
time="2023-09-30 12:14:05" level=info msg="BiliLive-go Version: v0.7.18 Link Start"
time="2023-09-30 12:14:05" level=info msg="Server start at :8080"
time="2023-09-30 12:31:03" level=info msg="Live Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 12:31:03" level=info msg="Record Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 15:00:53" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 15:00:55" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 15:01:02" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 15:01:02" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 15:01:02" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 15:01:12" level=info msg="exit status 1" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 22:26:13" level=info msg="Live Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 22:26:13" level=info msg="Record Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 23:49:20" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 23:49:20" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-09-30 23:49:20" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 00:08:31" level=info msg="Live Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 00:08:31" level=info msg="Record Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:01:32" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:01:43" level=info msg="exit status 1" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:20:34" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:20:44" level=info msg="exit status 1" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:20:46" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:20:46" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 02:20:54" level=info msg="exit status 1" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 09:43:35" level=info msg="Server close"
time="2023-10-01 09:43:35" level=info msg="Bye~"
time="2023-10-01 09:43:39" level=info msg="BiliLive-go Version: v0.7.18 Link Start"
time="2023-10-01 09:43:40" level=info msg="Server start at :8080"
time="2023-10-01 12:12:48" level=info msg="Live Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 12:12:48" level=info msg="Record Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:08:30" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:08:34" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:08:37" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:08:37" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:08:37" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:08:37" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 14:56:52" level=info msg="Live Start" host="张不才" room="张不才正在直播"
time="2023-10-01 14:56:52" level=info msg="Record Start" host="张不才" room="张不才正在直播"
time="2023-10-01 15:26:45" level=info msg="<nil>" host="张不才" room="张不才正在直播"
time="2023-10-01 15:26:58" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 15:26:58" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 15:27:26" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 19:08:59" level=error msg="failed to load room info" error="failed to get page, code: 504, internal error" url="https://live.douyin.com/zbcll0715"
time="2023-10-01 22:01:06" level=info msg="Live Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-01 22:01:06" level=info msg="Record Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 02:12:31" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 02:12:31" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 02:13:19" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 12:14:35" level=info msg="Live Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 12:14:35" level=info msg="Record Start" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 14:34:35" level=info msg="<nil>" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 14:34:44" level=info msg="Live end" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 14:34:44" level=info msg="Record End" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 14:34:45" level=info msg="exit status 1" host="张不才" room="CS2全方位讲解，张老师小课堂开课啦！"
time="2023-10-02 22:08:21" level=info msg="Live Start" host="张不才" room="张老师冲击完美TOP10？？？"
time="2023-10-02 22:08:21" level=info msg="Record Start" host="张不才" room="张老师冲击完美TOP10？？？"
time="2023-10-03 01:31:47" level=info msg="<nil>" host="张不才" room="张老师冲击完美TOP10？？？"
time="2023-10-03 01:31:51" level=info msg="<nil>" host="张不才" room="张老师冲击完美TOP10？？？"
time="2023-10-03 01:31:56" level=info msg="Live end" host="张不才" room="张老师冲击完美TOP10？？？"
time="2023-10-03 01:31:56" level=info msg="Record End" host="张不才" room="张老师冲击完美TOP10？？？"
time="2023-10-03 01:32:01" level=info msg="exit status 1" host="张不才" room="张老师冲击完美TOP10？？？"
```
### 自由描述

在确认有原画画质选项的情况下，大部分情况下会正常录制原画，但大概5场直播中有一场（如log中开始于2023-10-02 22:08:21的直播）会录制为720P30Fps的画质，已配置抖音Cookie，原因不明。
环境：腾讯云CVM 上海 2C4G 1Gpbs
