### ISSUE TITLE
[提问]: 请问怎么给b站加cookie  我的意思是复制到哪里，是配置文件里的括号里，还是删掉括号直接粘贴

### ISSUE THREAD

**Issue by menheng** [hr3lxphr6j/bililive-go#619]
### 程序版本

0.7.2

### 所使用的 config 文件的内容

cookies:{}

**Comment by Giftia** [comment]
键值形式。即：以域名为key，cookie为值，填入到 `{}` 里。
如：你的阿b的cookie获取到的是 `noob bilibili; abaabaaba`，那么应该是这样子的：
```yaml
cookies: {
  live.bilibili.com: noob bilibili; abaabaaba
}
```
